### ISSUE TITLE
python error

### ISSUE THREAD

**Issue by Mubassim** [lordofwizard/mcserver#5]
i am from youtube i had error with script.py

**Comment by Mubassim** [comment]
Traceback (most recent call last):
  File "script.py", line 1, in <module>
    from pynput.keyboard import Key, Controller
  File "/home/faaam208/.local/lib/python3.7/site-packages/pynput/__init__.py", line 40, in <module>
    from . import keyboard
  File "/home/faaam208/.local/lib/python3.7/site-packages/pynput/keyboard/__init__.py", line 31, in <module>
    backend = backend(__name__)
  File "/home/faaam208/.local/lib/python3.7/site-packages/pynput/_util/__init__.py", line 82, in backend
    if resolutions else '')
ImportError: this platform is not supported: ('failed to acquire X connection: Bad display name ""', DisplayNameError(''))

Try one of the following resolutions:

 * Please make sure that you have an X server running, and that the DISPLAY environment variable is set correctly
![image_2021-04-14_131756](https://user-images.githubusercontent.com/80640781/114677518-d3565a00-9d23-11eb-8bea-278bec6b193d.png)

**Comment by lordofwizard** [comment]
mate you have to open powershell in your windows computer... i don't know much about windows tho
but open powershell (you must have python installed on it btw)
then do these commands
```pip install pynput```
and then you need to download the script.py to your local windows 10 machine and then run the script init.. 
a tip... if you use cloudshell sdk it will be nice

**Comment by Mubassim** [comment]
bro but i want to play while server is running and i want to use my pc while server is on :(

**Comment by lordofwizard** [comment]
> bro but i want to play while server is running and i want to use my pc while server is on :(

Do you have a android phone?..  i use it to keep my server alive.. sometimes.. and we( me and my friends) we have a shitty laptop.. which runs debian btw. we use it to keep the server alive.. with that script.. with pynput.. if you got a another device lying around then that's great use it.. otherwise you have to do that manually :100:

**Comment by vaishnavkadam** [comment]
Hey, I know how to keep the server alive 24/7 without doing anything on our pc !!

You just have to terminate the screen to do so the server should be started and use this command

screen -s mcs java -Xmx6000M -Xms4000M -jar server.jar nogui

(Xmx = Max RAM)
(Xms = Min RAM)

Note that be sure to be in the mcserver directory!.

Thank you
-Vaishnav R Kadam

**Comment by Mubassim** [comment]
Bro Any way because i dont want to pay the electricity bills
